### ISSUE TITLE
Create succinct proof problem statement for CBR

### ISSUE THREAD

**Issue by Jinglan** [plasma-group/plasma#85]
Do a comprehensive writeup to provide to Dan and his students that delineates the problem space and all of our constraints.

**Comment by karlfloersch** [comment]
Feel free to grab anything from this workshop presentation -- https://docs.google.com/presentation/d/1SyrAbr3fX4HVwWQToafixt38Tsgwgrr4mqT2MVzHD1A/edit?usp=sharing
